#!/usr/bin/php
<?php

if (php_sapi_name() !== 'cli') {
    exit;
}
define('PROJECT_ROOT', dirname(__FILE__));

use Rahisi\Commands\App;
use Symfony\Component\Dotenv\Dotenv;


require __DIR__ . '/vendor/autoload.php';
include "./App/Helper.php";
$dotenv = new Dotenv();
$dotenv->load(__DIR__.'/.env');

$app = new App();

try {
    $app->runCommand($argv);
} catch (\Throwable $th) {
    throw $th;
}